# Generated by Django 5.2.4 on 2025-07-16 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50)),
                ('author', models.TextField(max_length=60)),
                ('description', models.TextField(max_length=250)),
                ('post_image', models.CharField(max_length=50)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
